module.exports = [
  {
    _id: 1,
    name: 'Jane Doe',
    careerPath: 'UX Design',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Warsaw',
    why: 'Lorem ipsum lorem ipsum lorem ipsum.',
    goals: 'Lorem ipsum lorem ipsum lorem ipsum.',
    supportNeeded: 'Lorem ipsum lorem ipsum lorem ipsum.',
    prep: 'Lorem ipsum lorem ipsum lorem ipsum.',
    time: '50 - 100 hours',
    determination: 'Lorem ipsum lorem ipsum lorem ipsum.',
    work: 'Lorem ipsum lorem ipsum lorem ipsum.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Currently not working',
    profession: 'Architect',
    age: '26-30',
    mom: true,
    other: 'Lorem ipsum lorem ipsum lorem ipsum.',
    // change to relational DB: my_mentor (one mentee to one mentor), bookmarked (many mentees to many mentors)
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 2,
    name: 'John Doe',
    careerPath: 'Frontend Development',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Kraków',
    why: 'Hello hello hello hello hello.',
    goals: 'Hello hello hello hello hello.',
    supportNeeded: 'Hello hello hello hello hello.',
    prep: 'Hello hello hello hello hello.',
    time: '100 - 150 hours',
    determination: 'Lorem ipsum lorem ipsum lorem ipsum.',
    work: 'Lorem ipsum lorem ipsum lorem ipsum.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Working',
    profession: 'Historian',
    age: '31-35',
    mom: true,
    other: 'Hello hello hello hello hello',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 3,
    name: 'Marie Doe',
    careerPath: 'Backend Development',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Kraków',
    why: 'Bye bye bye bye.',
    goals: 'Bye bye bye bye.',
    supportNeeded: 'Bye bye bye bye.',
    prep: 'Bye bye bye bye.',
    time: '100 - 150 hours',
    determination: 'Lorem ipsum lorem ipsum lorem ipsum.',
    work: 'Lorem ipsum lorem ipsum lorem ipsum.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Working',
    profession: 'Historian',
    age: '31-35',
    mom: true,
    other: 'Bye bye bye bye',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 4,
    name: 'John Doe',
    careerPath: 'Frontend Development',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Kraków',
    why: 'Whatup Whatup Whatup Whatup.',
    goals: 'Whatup Whatup Whatup Whatup.',
    supportNeeded: 'Whatup Whatup Whatup Whatup.',
    prep: 'Whatup Whatup Whatup Whatup.',
    time: '100 - 150 hours',
    determination: 'Whatup Whatup Whatup Whatup.',
    work: 'Whatup Whatup Whatup Whatup.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Working',
    profession: 'Historian',
    age: '31-35',
    mom: true,
    other: 'Whatup Whatup Whatup Whatup',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 5,
    name: 'Jane Doe',
    careerPath: 'UX Design',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Warsaw',
    why: 'Lorem ipsum lorem ipsum lorem ipsum.',
    goals: 'Lorem ipsum lorem ipsum lorem ipsum.',
    supportNeeded: 'Lorem ipsum lorem ipsum lorem ipsum.',
    prep: 'Lorem ipsum lorem ipsum lorem ipsum.',
    time: '50 - 100 hours',
    determination: 'Lorem ipsum lorem ipsum lorem ipsum.',
    work: 'Lorem ipsum lorem ipsum lorem ipsum.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Currently not working',
    profession: 'Architect',
    age: '26-30',
    mom: true,
    other: 'Lorem ipsum lorem ipsum lorem ipsum.',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 6,
    name: 'John Doe',
    careerPath: 'Frontend Development',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Kraków',
    why: 'Hello hello hello hello hello.',
    goals: 'Hello hello hello hello hello.',
    supportNeeded: 'Hello hello hello hello hello.',
    prep: 'Hello hello hello hello hello.',
    time: '100 - 150 hours',
    determination: 'Lorem ipsum lorem ipsum lorem ipsum.',
    work: 'Lorem ipsum lorem ipsum lorem ipsum.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Working',
    profession: 'Historian',
    age: '31-35',
    mom: true,
    other: 'Hello hello hello hello hello',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 7,
    name: 'Marie Doe',
    careerPath: 'Backend Development',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Kraków',
    why: 'Bye bye bye bye.',
    goals: 'Bye bye bye bye.',
    supportNeeded: 'Bye bye bye bye.',
    prep: 'Bye bye bye bye.',
    time: '100 - 150 hours',
    determination: 'Lorem ipsum lorem ipsum lorem ipsum.',
    work: 'Lorem ipsum lorem ipsum lorem ipsum.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Working',
    profession: 'Historian',
    age: '31-35',
    mom: true,
    other: 'Bye bye bye bye',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
  {
    _id: 8,
    name: 'John Doe',
    careerPath: 'Frontend Development',
    linkedin: 'https://www.linkedin.com/in/natalie-pilling/',
    town: 'Kraków',
    why: 'Whatup Whatup Whatup Whatup.',
    goals: 'Whatup Whatup Whatup Whatup.',
    supportNeeded: 'Whatup Whatup Whatup Whatup.',
    prep: 'Whatup Whatup Whatup Whatup.',
    time: '100 - 150 hours',
    determination: 'Whatup Whatup Whatup Whatup.',
    work: 'Whatup Whatup Whatup Whatup.',
    video: 'https://www.loom.com/share/4d2d9ee60b244680bc061ef711528dc1',
    employment: 'Working',
    profession: 'Historian',
    age: '31-35',
    mom: true,
    other: 'Whatup Whatup Whatup Whatup',
    bookmarked: false,
    chosen: false,
    chosenByMe: false,
  },
];
